"""Add unique title

Revision ID: 428fac137bf8
Revises: b77c3706fc0f
Create Date: 2024-01-22 17:21:13.222372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428fac137bf8'
down_revision: Union[str, None] = 'b77c3706fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dishes', ['title'])
    op.create_unique_constraint(None, 'menus', ['title'])
    op.create_unique_constraint(None, 'submenus', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='unique')
    op.drop_constraint(None, 'menus', type_='unique')
    op.drop_constraint(None, 'dishes', type_='unique')
    # ### end Alembic commands ###
