"""Change id on UUID

Revision ID: b77c3706fc0f
Revises: 9ede7ce8bb97
Create Date: 2024-01-22 16:14:55.777943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77c3706fc0f'
down_revision: Union[str, None] = '9ede7ce8bb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
